CREATE DATABASE IF NOT EXISTS wordpress;

CREATE USER IF NOT EXISTS 'amoubare'@'%' IDENTIFIED BY 'popo333';

GRANT ALL PRIVILEGES ON wordpress.* TO 'amoubare'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'ABCD123'


